"""fix Categories-Products relationship

Revision ID: 1e7d6ec4d3de
Revises: 672b0641c461
Create Date: 2026-09-15 15:21:36.776696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e7d6ec4d3de'
down_revision = '672b0641c461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_product_category_id_category'), 'category', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_product_category_id_category'), type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
