"""added Categories

Revision ID: 672b0641c461
Revises: 8686a510a328
Create Date: 2026-09-15 14:57:00.542361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '672b0641c461'
down_revision = '8686a510a328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###
